### ISSUE TITLE
Storing Laws and Regulations

### ISSUE THREAD

**Issue by kaerumy** [Sinar/sinarngo#30]
Legal reform is a key goal, we will therefore need to be able to link, knowledge resources to specific laws and sections in laws.

Review Legal Matter Standard Specification (LMSS) and find out if they have some class/schema definitions on how law and sections in laws are stored or looked up.

https://sali.org/Review-the-SALI-Standard

**Comment by samqi** [comment]
SALI LMSS is a standard that defines a set of tags that describe legal matters using four main categories: area of law, service, forum, and other. However, SALI LMSS does not provide class schema definitions for how law and sections of law are stored or looked up. Instead, it relies on external sources and references to provide the details and links to the relevant legal documents.
Note: [Current version is LMSS 2.0](https://github.com/sali-legal/LMSS) 

For example, if you want to tag a legal matter that involves the section 51 of the Malaysian Anti-Corruption Commission Act 2009, which deals with the protection of informers, you can use the following tags from SALI LMSS:
Area of Law: Anti-Corruption Law
Service: Advisory
Forum: Malaysia
Other: Anti-Corruption Commission Act
WebProtege reference view:
![image](https://github.com/Sinar/sinarngo/assets/14970534/0ec15d85-7dc6-43c5-bd88-3c0944416dcd)
![image](https://github.com/Sinar/sinarngo/assets/14970534/76a0b58f-abb3-4587-a56d-e5b56e4992d2)
![image](https://github.com/Sinar/sinarngo/assets/14970534/b0a3f19f-fd21-46aa-a4df-33fcbbe3f9ae)

The tags are represented by unique identifiers (IRIs) that can be used to query and exchange data using the SALI API standard. These IRI are optimised for machines & are not in human readable form. For example, the IRI for Anti-Corruption Law is  http://lmss.sali.org/R8afVWfZ0cr5TifIBZTdpL2.

 You can determine the IRI with [the Stanford WebProtégé tool link as per earlier link] or you can find the IRIs for each tag in the LMSS.owl file](https://github.com/sali-legal/LMSS/blob/main/LMSS.owl). A final option is to use a [Python SALI LMSS tool ](https://github.com/273v/python-lmss) by the team who created a [KELVIN legal data stack for SALI LMSS](https://docs.kelvin.legal/docs/introduction/intro/).
 


However, to specify the section 51 of the Malaysian Anti-Corruption Commission Act 2009, you need to use an external source or reference that provides the information and URL of the legal document. [For example, you can use the Attorney General’s Chambers of Malaysia website](https://lom.agc.gov.my/)[3](https://lom.agc.gov.my/), which is a free online database of federal legislation in Malaysia. You can search for the Malaysian Anti-Corruption Commission Act 2009 on the website and find the URL for section 51, which is https://lom.agc.gov.my/act/694#section51. You can then use this URL as a reference for your legal matter tag.

**Comment by samqi** [comment]
1. Akoma Ntoso [is XML based](https://medium.com/@bungeni/why-is-akoma-ntoso-in-xml-and-not-html-or-json-or-pdf-8fb0ff0a9dd2), and [Class/schema definitions for Akoma Ntosa are provided by LegalDocML. Current Version is 3.0](http://www.akomantoso.org/?page_id=27).  Akoma Ntoso uses [LegalDocML ](https://github.com/oasis-open/legaldocml-akomantoso/tree/master/csprd02-part2-specs) in its standard because LegalDocML is the[ name of the OASIS technical committee that developed and maintains the Akoma Ntoso standard](https://docs.oasis-open.org/legaldocml/akn-nc/v1.0/os/akn-nc-v1.0-os.html#_Toc531692276).

2. LegalDocML stands for Legal Document Markup Language, which is a generic term for any XML-based language that represents legal documents. [Akoma Ntoso is a specific instance of LegalDocML that defines a set of XML representations for executive, legislative and judiciary documents, such as laws, cases, judgments, etc](https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=legaldocml). Akoma Ntoso is also the name of the root element of the XML schema that specifies the structure and components of legal documents. Therefore, Akoma Ntoso and LegalDocML are not separate or competing standards, but rather different names for the same standard that reflect its origin and scope.

3. Sample [Schema](https://github.com/oasis-open/legaldocml-akomantoso/tree/master/csprd02-part2-specs/csprd02-part2-specs-schemas) & [Examples ](https://github.com/oasis-open/legaldocml-akomantoso/tree/master/csprd02-part2-specs/csprd02-part2-specs-examples) from [Oasis-Open  Github legaldocml-akomantoso repository](https://github.com/oasis-open/legaldocml-akomantoso) using the latest standards

4. Akoma Ntoso [examples browser by University Of Bologna - CIRSFID](http://sinatra.cirsfid.unibo.it/XMLViewer/) for older version of Akoma Ntoso.

5. [United Nation System for Akoma Ntoso CEB github site](https://unsceb-hlcm.github.io/) has comprehensive documentation for "[technical specifications](https://unsceb-hlcm.github.io/part1/)" "[document modelling](https://unsceb-hlcm.github.io/part2/)" and "[united nations system document ontology](https://unsceb-hlcm.github.io/onto-undo/)". 
[UNSCED-HLCM stands for United Nations System Chief Executives Board for Coordination - High-Level Committee on Management](https://unsceb.org/high-level-committee-management-hlcm)[1](https://unsceb.org/high-level-committee-management-hlcm). [It is a committee that identifies and analyzes administrative management reforms with the aim of improving efficiency and simplifying business practices across the United Nations system](https://unsceb.org/high-level-committee-management-hlcm)

**Comment by samqi** [comment]
To link knowledge resources to specific laws and sections in laws similar to Popolo, you can use the Akoma Ntoso standard, which provides a set of XML representations for executive, legislative and judiciary documents. Akoma Ntoso uses two kinds of schema:

- The Akoma Ntoso general schema is the vocabulary of elements and attributes, as well as the minimal set of constraints that all Akoma Ntoso documents must comply to. It defines the main structure and components of legal documents, such as the `<akomaNtoso>` root element, the `<meta>` element for metadata, the `<preface>` element for introductory information, the `<body>` element for the main content, and the `<components>` element for additional components¹.
- The Akoma Ntoso custom schemas are an open set of stricter schemas providing more constraints over the same vocabulary of elements and attributes depending on the wishes of their designers. They are meant to enforce the rules of specific document types in specific jurisdictions, and as such may enforce a larger number of requirements and constraints than the general schema. For example, there are custom schemas for different types of legal documents, such as act, bill, case, judgment, etc².

To store or look up law and sections in laws, you need to use the appropriate elements and attributes from the Akoma Ntoso schema that describe the legal document and its parts. For example, if you want to store or look up section 5[1](http://www.akomantoso.org/?page_id=47) of the Malaysian Anti-Corruption Commission Act [2](http://www.akomantoso.org/?page_id=27)009, which deals with the protection of informers, you can use the following elements and attributes from the Akoma Ntoso schema:

- The `<act>` element to represent the legal document type
- The `<FRBRWork>` element to provide information about the work level of the legal document
- The `<FRBRExpression>` element to provide information about the expression level of the legal document
- The `<FRBRManifestation>` element to provide information about the manifestation level of the legal document
- The `<identification>` element to provide identifiers for the legal document
- The `<publication>` element to provide information about the official publication of the legal document
- The `<references>` element to provide references to external resources related to the legal document
- The `<part>` element to represent a subdivision of the legal document
- The `<chapter>` element to represent a subdivision of a part
- The `<section>` element to represent a subdivision of a chapter
- The `num` attribute to provide a number for a subdivision
- The `name` attribute to provide a name for a subdivision
- The `eId` attribute to provide an identifier for an element
- The `href` attribute to provide a link to an external resource

For example, you can store or look up section 51 of the Malaysian Anti-Corruption Commission Act 2009 using Akoma Ntoso like this:

    <akomaNtoso xmlns="http://docs.oasis-open.org/legaldocml/ns/akn/3.0">
      <act name="Malaysian Anti-Corruption Commission Act 2009">
        <meta>
          <identification source="#somebody">
            <FRBRWork>
              <FRBRthis value="/my/act/2009/694/!main"/>
              <FRBRuri value="/my/act/2009/694"/>
              <FRBRalias value="Malaysian Anti-Corruption Commission Act 2009" name="title"/>
              <FRBRdate date="2009-08-01" name="Generation"/>
              <FRBRauthor href="#somebody" as="#author"/>
              <FRBRcountry value="my"/>
            </FRBRWork>
            <FRBRExpression>
              <FRBRthis value="/my/act/2009/694/eng@2018-09-01/!main"/>
              <FRBRuri value="/my/act/2009/694/eng@2018-09-01"/>
              <FRBRdate date="2018-09-01" name="Revision"/>
              <FRBRauthor href="#somebody" as="#editor"/>
              <FRBRlanguage language="eng"/>
            </FRBRExpression>
            <FRBRManifestation>
              <FRBRthis value="/my/act/2009/694/eng@2018-09-01/main.xml"/>
              <FRBRuri value="/my/act/2009/694/eng@2018-09-01/main.xml"/>
              <FRBRdate date="2018-09-01" name="Generation"/>
              <FRBRauthor href="#somebody" as="#editor"/>
            </FRBRManifestation>
          </identification>
          <publication date="2018-09-01" name="Federal Government Gazette" number="694" showAs="Malaysian Anti-Corruption Commission Act 2009 (Act 694)" source="#somebody"/>
          <references source="#somebody">
            <TLCOrganization eId="somebody" href="http://www.somebody.com" showAs="Somebody"/>
          </references>
        </meta>
        <body>
          <part eId="part_1" name="PRELIMINARY">
            <chapter eId="chp_1" name="PRELIMINARY">
              <section eId="sec_1" num="1">
                <num>1.</num>
                <heading>Short title and commencement</heading>
                <content>
                  <p>(1) This Act may be cited as the Malaysian Anti-Corruption Commission Act 2009.</p>
                  <p>(2) This Act comes into operation on a date to be appointed by the Minister by notification in the Gazette.</p>
                </content>
              </section>
              
            </chapter>
            
          </part>
          
          <part eId="part_6" name="MISCELLANEOUS">
            <chapter eId="chp_6" name="MISCELLANEOUS">
              
              <section eId="sec_51" num="51">
                <num>51.</num>
                <heading>Protection of informers</heading>
                <content>
                  <p>(1) Except as hereinafter provided, no complaint as to an offence under this Act shall be admitted in evidence in any civil or criminal proceeding whatsoever, and no witness shall be obliged or permitted to disclose the name or address of any informer, or state any matter which might lead to his discovery.</p>
                  <p>(2) If any books, documents or papers which are in evidence or liable to inspection in any civil or criminal proceeding whatsoever contain any entry in which any informer is named or described or which might lead to his discovery, the court shall cause all such passages to be concealed from view or to be obliterated so far as is necessary to protect the informer from discovery, but no further.</p>
                  <p>(3) If on a trial for any offence under this Act the court, after full inquiry into the case, is of the opinion that the informer wilfully made in his complaint a material statement which he knew or believed to be false or did not believe to be true, or if in any other proceeding the court is of the opinion that justice cannot be fully done between the parties thereto without the discovery of the informer, it shall be lawful for the court to require the production of the original complaint, if in writing, and permit inquiry and require full disclosure concerning the informer.</p>
                </content>
              </section>
              
            </chapter>
            
          </part>
          
        </body>
      </act>
    </akomaNtoso>

[You can find more information and examples on how to store or look up law and sections in laws in Akoma Ntoso on its website](http://www.akomantoso.org/?page_id=47) or in its documentation.
